### PR TITLE
Update YMRA-ELA.yml

### PR DESCRIPTION
**Pull request by YMRA-ELA**

### CODE REVIEW

**Comment by YMRA-ELA** [comment]
I have completed all tests in the course and received over 70% correct responses, but I am not able to make an automated request to receive a certificate of completion for this course. Please help.

**Review by YMRA-ELA — COMMENTED** [review]
I have completed all tests in the course and received over 70% correct responses, but I am not able to make an automated request to receive a certificate of completion for this course. Please help.

**Comment by afewell** [comment]
Hi @YMRA-ELA so sorry for my delayed response. I am not sure what went wrong, but as we are removing testing and badging from the site, I went ahead and manually provisioned this badge for you. 

You should be able to see the badge award in your badgr.com profile associated with the mcsefung@gmail.com email address. 

Thanks!

**Comment by YMRA-ELA** [comment]
Thank you.

**Pull request closed without merging**
